Update cherry_pick.yml

diff --git a/.github/workflows/cherry_pick.yml b/.github/workflows/cherry_pick.yml
--- a/.github/workflows/cherry_pick.yml
+++ b/.github/workflows/cherry_pick.yml
@@ -57,14 +57,14 @@ jobs:
           python-version: '3.x'
 
       # Step 5: Debugging Step - Check if requirements.txt exists
-      - name: Check if requirements.txt exists
-        run: |
-          if exist scripts/requirements.txt (
-            echo "requirements.txt found"
-          ) else (
-            echo "requirements.txt not found"
-            exit 1
-          )
+      # - name: Check if requirements.txt exists
+      #   run: |
+      #     if exist scripts/requirements.txt (
+      #       echo "requirements.txt found"
+      #     ) else (
+      #       echo "requirements.txt not found"
+      #       exit 1
+      #     )
 
       # Step 6: Install Requirements for the scripts
       - name: Install Requirements
